// src/app/api/generate-plan/route.tsx
import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import { Resend } from "resend";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
  baseURL: process.env.OPENAI_BASE_URL || "https://api.openai.com/v1",
  defaultHeaders: {
    'HTTP-Referer': 'http://localhost:3000',
    'X-Title': 'AI Fitness Wizard'
  },
});
const resend = new Resend(process.env.RESEND_API_KEY!);

// Enhanced PDF Styles
const pdfStyles = StyleSheet.create({
  page: { padding: 0, fontSize: 12, fontFamily: "Helvetica", backgroundColor: "#ffffff" },
  header: {
    backgroundColor: "#7c3aed",
    padding: 40,
    paddingBottom: 30,
    marginBottom: 30,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 14,
    color: "#e9d5ff",
    opacity: 0.9,
  },
  content: {
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  section: {
    marginBottom: 25,
    padding: 20,
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    borderLeft: "4px solid #7c3aed",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#4c1d95",
    marginBottom: 15,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  field: {
    width: "48%",
    marginBottom: 10,
  },
  label: {
    fontSize: 10,
    color: "#64748b",
    marginBottom: 2,
    textTransform: "uppercase",
  },
  value: {
    fontSize: 12,
    color: "#1e293b",
    fontWeight: "bold",
  },
  planText: {
    fontSize: 11,
    lineHeight: 1.6,
    color: "#334155",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    color: "#94a3b8",
    fontSize: 10,
    borderTop: "1px solid #e2e8f0",
    paddingTop: 20,
  },
});

const FitnessPDF = ({ data, plan }: { data: any; plan: string }) => (
  <Document>
    <Page size="A4" style={pdfStyles.page}>
      {/* Header */}
      <View style={pdfStyles.header}>
        <Text style={pdfStyles.headerTitle}>Fitness Wizard Plan</Text>
        <Text style={pdfStyles.headerSubtitle}>Customized for {data.name}</Text>
      </View>

      <View style={pdfStyles.content}>
        {/* Profile Section */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>Athlete Profile</Text>
          <View style={pdfStyles.row}>
            <View style={pdfStyles.field}>
              <Text style={pdfStyles.label}>Goal</Text>
              <Text style={pdfStyles.value}>{data.goal.replace(/_/g, " ").toUpperCase()}</Text>
            </View>
            <View style={pdfStyles.field}>
              <Text style={pdfStyles.label}>Fitness Level</Text>
              <Text style={pdfStyles.value}>{data.fitnessLevel.toUpperCase()}</Text>
            </View>
            <View style={pdfStyles.field}>
              <Text style={pdfStyles.label}>Timeline</Text>
              <Text style={pdfStyles.value}>{data.timeline.replace(/_/g, " ").toUpperCase()}</Text>
            </View>
            <View style={pdfStyles.field}>
              <Text style={pdfStyles.label}>Equipment</Text>
              <Text style={pdfStyles.value}>{data.equipment.join(", ") || "Bodyweight Only"}</Text>
            </View>
          </View>
        </View>

        {/* Plan Section */}
        <View style={{ ...pdfStyles.section, backgroundColor: "#fff", borderLeft: "4px solid #ec4899" }}>
          <Text style={{ ...pdfStyles.sectionTitle, color: "#be185d" }}>Your 4-Week Blueprint</Text>
          <Text style={pdfStyles.planText}>{plan}</Text>
        </View>
      </View>

      {/* Footer */}
      <Text style={pdfStyles.footer}>
        Generated by AI Fitness Wizard • {new Date().toLocaleDateString()} • Stay Consistent!
      </Text>
    </Page>
  </Document>
);

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { want, ...formData } = body;

    // Generate AI plan
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: "You are a world-class fitness coach. Write a detailed, motivating 4-week plan with workouts and meals. Use markdown. Be encouraging." },
        { role: "user", content: JSON.stringify(formData, null, 2) }
      ],
      temperature: 0.8,
      max_tokens: 2000
    });

    const aiPlan = completion.choices[0].message.content!;

    // Generate PDF
    const pdfDoc = <FitnessPDF data={formData} plan={aiPlan} />;
    const pdfBlob = await pdf(pdfDoc).toBlob();
    const pdfBuffer = Buffer.from(await pdfBlob.arrayBuffer());

    const response: any = { success: true, message: "Plan ready!" };

    // Email with PDF
    if (want?.email) {
      await resend.emails.send({
        from: "AI Fitness Wizard <plan@yourdomain.com>",
        to: formData.email,
        subject: `Your Custom Fitness Plan is Here, ${formData.name.split(" ")[0]}!`,
        html: `
          <h1>Congrats, ${formData.name.split(" ")[0]}!</h1>
          <p>Here’s your personalized 4-week fitness + nutrition plan.</p>
          <pre style="background:#f9f9f9;padding:20px;border-radius:8px;font-size:14px;">${aiPlan}</pre>
          <p>You’ve got this!</p>
        `,
        attachments: [{
          filename: "Your_AI_Fitness_Plan.pdf",
          content: pdfBuffer
        }]
      });
    }

    // Add PDF for download
    if (want?.pdf) {
      response.pdfUrl = `data:application/pdf;base64,${pdfBuffer.toString("base64")}`;
    }

    return NextResponse.json(response);

  } catch (error: any) {
    console.error("Generate plan error:", error);
    return NextResponse.json(
      { error: "Failed to generate plan. Try again!" },
      { status: 500 }
    );
  }
}