"use client";

import { useRouter } from "next/navigation";
import Link from "next/link";

export default function TermsAndConditions() {
    const router = useRouter();

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-gray-950 transition-colors py-12 px-6">
            <div className="max-w-3xl mx-auto bg-white dark:bg-gray-900 rounded-3xl shadow-xl p-8 md:p-12">
                {/* Navigation */}
                <div className="mb-8 flex justify-between items-center">
                    <button
                        onClick={() => router.back()}
                        className="inline-flex items-center text-sm font-semibold text-purple-600 dark:text-purple-400 hover:text-purple-700 dark:hover:text-purple-300 transition-colors"
                    >
                        ← Back
                    </button>
                    <Link href="/privacy" className="text-sm font-semibold text-purple-600 dark:text-purple-400 hover:text-purple-700 transition-colors">
                        Privacy Policy →
                    </Link>
                </div>

                {/* Content */}
                <article className="prose prose-lg dark:prose-invert max-w-none prose-headings:font-bold prose-h1:text-transparent prose-h1:bg-clip-text prose-h1:bg-gradient-to-r prose-h1:from-purple-600 prose-h1:to-pink-600 prose-a:text-purple-600 dark:prose-a:text-purple-400">
                    <h1>Terms & Conditions</h1>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Last updated: February 27, 2026</p>

                    <p>By using RamaFit (ramafit.xyz), you agree to these Terms & Conditions. Please read them carefully before purchasing.</p>

                    <h2>1. What We Sell</h2>
                    <p>RamaFit sells AI-generated, personalized fitness and nutrition plans delivered as downloadable PDF documents and emailed to you. Our products are:</p>
                    <ul>
                        <li><strong>Starter Plan ($4.99):</strong> A complete 4-week personalized training and nutrition plan with daily workouts, meal plans with macros, and coaching notes</li>
                        <li><strong>Transform Plan ($14.99):</strong> The full 4-week starter plan plus a 3-month progression roadmap with workout and nutrition adjustments</li>
                        <li><strong>Elite Plan ($29.99):</strong> The full 4-week starter plan plus a 6-month periodized journey with three distinct training phases</li>
                    </ul>
                    <p>All purchases are <strong>one-time payments</strong> — there are no subscriptions, recurring charges, or hidden fees.</p>

                    <h2>2. Free Sample</h2>
                    <p>We offer a free 1-week sample plan (Week 1 only) limited to one per person. The free sample is provided as-is and does not include email delivery, macros, coaching notes, or subsequent weeks.</p>

                    <h2>3. Digital Product Delivery</h2>
                    <p>After successful payment, your plan is generated by our AI system and delivered to you via:</p>
                    <ul>
                        <li>A downloadable PDF on the confirmation page</li>
                        <li>An email to the address you provided during checkout</li>
                    </ul>
                    <p>Delivery typically takes 1–3 minutes after payment. If you do not receive your plan within 10 minutes, please contact us.</p>

                    <h2>4. AI-Generated Content Disclaimer</h2>
                    <p>All plans are generated using artificial intelligence (OpenAI GPT-4o-mini) based on the information you provide. While our AI produces high-quality, personalized plans:</p>
                    <ul>
                        <li>Plans are <strong>not</strong> a substitute for professional medical advice, diagnosis, or treatment</li>
                        <li>Consult your doctor before starting any new fitness or nutrition program, especially if you have pre-existing health conditions</li>
                        <li>We are not responsible for injuries, health issues, or results from following the plan</li>
                        <li>Results may vary based on individual effort, consistency, and biological factors</li>
                    </ul>

                    <h2>5. Intellectual Property</h2>
                    <p>Each plan is uniquely generated for you. You receive a personal, non-transferable license to use your plan for your own personal fitness goals. You may not resell, redistribute, or commercially reproduce the plan content.</p>

                    <hr className="my-8 border-gray-200 dark:border-gray-800" />

                    <h1>Refund Policy</h1>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Last updated: February 27, 2026</p>

                    <p>Because our plans are <strong>digital products generated instantly and uniquely for you</strong>, we generally cannot offer refunds once the plan has been delivered. However, we believe in fairness:</p>

                    <h2>When We Will Issue a Refund</h2>
                    <ul>
                        <li><strong>Non-delivery:</strong> If you paid but did not receive your plan PDF (via download or email) within 24 hours, we will issue a full refund</li>
                        <li><strong>Technical failure:</strong> If the PDF is corrupted, blank, or clearly not functional, we will regenerate it or issue a full refund</li>
                        <li><strong>Duplicate charges:</strong> If you were accidentally charged twice for the same plan, we will refund the duplicate charge immediately</li>
                    </ul>

                    <h2>When We Cannot Issue a Refund</h2>
                    <ul>
                        <li>You have already downloaded or received the plan by email</li>
                        <li>You simply changed your mind after receiving the plan</li>
                        <li>You are unsatisfied with AI-generated content quality (please try the free sample first to evaluate)</li>
                    </ul>

                    <h2>How to Request a Refund</h2>
                    <p>Email <a href="mailto:hello@ramafit.xyz">hello@ramafit.xyz</a> with:</p>
                    <ul>
                        <li>Your name and email used for the purchase</li>
                        <li>A description of the issue</li>
                        <li>Your order/receipt number (from Lemon Squeezy)</li>
                    </ul>
                    <p>We aim to respond within 48 hours and process approved refunds within 5–7 business days.</p>

                    <hr className="my-8 border-gray-200 dark:border-gray-800" />

                    <h2>Contact</h2>
                    <p className="font-medium">
                        Questions about these terms or need support? Email us at <a href="mailto:hello@ramafit.xyz">hello@ramafit.xyz</a>.
                    </p>
                </article>
            </div>
        </div>
    );
}
